// Phase "emit": turn the walked graphs into flake.nix text. Every check has already run, so nothing
// here reports user errors.
import { attrName, indent } from "../ast/format.js"
import type { Input } from "../ast/input.js"
import { EmitContext, type Node } from "../ast/node.js"
import { Str } from "../ast/str.js"
import type { Definition } from "../api/definition.js"
import { CATEGORIES, type SystemGraph } from "./expand.js"
import type { Names } from "./naming.js"
import type { WalkResult } from "./walk.js"

const HEADER = "# Generated by nixty. Edit the nixty file it comes from instead; this file is overwritten."

/**
 * The whole flake:
 *
 *     {
 *       description = "...";
 *       inputs = { ... };
 *       outputs = { self, nixpkgs, ... }:
 *         let
 *           perSystem = { <system> = let <shared nodes> in { packages = ...; devShells = ...; }; };
 *         in
 *         { packages = builtins.mapAttrs (_: s: s.packages) perSystem; ... };
 *     }
 */
export function emitFlake(definition: Definition, graphs: SystemGraph[], walked: WalkResult, names: Names): string {
    const categories = CATEGORIES.filter((c) => graphs.some((g) => g.outputs.some((o) => o.category === c)))
    const plain = new EmitContext(new Map())

    const perSystem = graphs.map((graph): [string, string] => {
        const lets = names.lets.get(graph.system) ?? new Map<Node, string>()
        const ctx = new EmitContext(new Map<Node, string>([...names.inputs, ...lets]))
        const body = categories.map((category): [string, string] => {
            const outputs = graph.outputs.filter((o) => o.category === category)
            return [category, attrSet(outputs.map((o) => [o.name, ctx.emit(o.node)]))]
        })
        const facts = walked.systems.find((s) => s.system === graph.system)
        // A `let` line is the node's own code: `ctx.emit` would give back its name.
        const bindings = (facts?.order ?? [])
            .filter((node) => lets.has(node))
            .map((node): [string, string] => [lets.get(node)!, node.emit(ctx)])
        return [graph.system, letIn(bindings, attrSet(body))]
    })

    const args = ["self", ...walked.inputs.map((input) => names.inputs.get(input)!), "..."]
    const outputs = attrSet(categories.map((c) => [c, `builtins.mapAttrs (_: s: s.${c}) perSystem`]))
    const outputsFn = [
        `{ ${args.join(", ")} }:`,
        letIn([["perSystem", attrSet(perSystem, true)]], outputs),
    ].join("\n")

    const sections = [
        `  description = ${indent(plain.emit(new Str([definition.description])))};`,
        `  inputs = ${indent(inputsBlock(walked, names.inputs, plain))};`,
        `  outputs =\n${pad(outputsFn, "    ")};`,
    ]
    return `${HEADER}\n{\n${sections.join("\n\n")}\n}\n`
}

/** `name.url = "...";` for a flake, and `flake = false` for any other input. */
function inputsBlock(walked: WalkResult, names: Map<Input, string>, ctx: EmitContext): string {
    return attrSet(
        walked.inputs.map((input): [string, string] => {
            const url = ctx.emit(new Str([input.url]))
            const name = names.get(input)!
            if (walked.flakeInputs.has(input)) return [`${name}.url`, url]
            return [name, attrSet([["url", url], ["flake", "false"]])]
        }),
        false,
        true,
    )
}

/**
 * `{ name = code; ... }`, one entry per line. `ownLine` puts each value on the line after its name, as
 * done for `let` blocks. Names are quoted when needed, unless `rawNames` (for `a.url`).
 */
function attrSet(entries: [string, string][], ownLine = false, rawNames = false): string {
    if (entries.length === 0) return "{ }"
    const lines = entries.map(([name, code]) => {
        const key = rawNames ? name : attrName(name)
        return ownLine ? `  ${key} =\n${pad(code, "    ")};` : `  ${key} = ${indent(code)};`
    })
    return `{\n${lines.join("\n")}\n}`
}

/** `let <bindings> in <body>`, or just `body` when there's nothing to bind. */
function letIn(bindings: [string, string][], body: string): string {
    if (bindings.length === 0) return body
    const lines = bindings.map(([name, code]) => `  ${name} = ${indent(code)};`)
    return `let\n${lines.join("\n")}\nin\n${body}`
}

/** Every non-empty line of `code` with `prefix` in front. */
function pad(code: string, prefix: string): string {
    return code
        .split("\n")
        .map((line) => (line === "" ? line : prefix + line))
        .join("\n")
}
