# Generated by nixty. Edit the nixty file it comes from instead; this file is overwritten.
{
  description = "Example 05: another flake as input";

  inputs = {
    nixpkgs = {
      url = "github:NixOS/nixpkgs/nixos-25.05";
      flake = false;
    };
    home-manager.url = "github:nix-community/home-manager/release-25.05";
  };

  outputs =
    { self, nixpkgs, home-manager, ... }:
    let
      perSystem = {
        x86_64-linux =
          let
            pkgs = import nixpkgs {
              system = "x86_64-linux";
              config = {
                allowUnfree = true;
              };
            };
          in
          {
            devShells = {
              home = pkgs.mkShell {
                name = "home";
                packages = [ home-manager.packages.x86_64-linux.home-manager ];
              };
            };
            apps = {
              hm-version = {
                type = "app";
                program = pkgs.lib.getExe (pkgs.writeShellApplication {
                  name = "hm-version";
                  runtimeInputs = [ home-manager.packages.x86_64-linux.home-manager ];
                  text = ''
                    home-manager --version
                  '';
                });
              };
            };
          };
      };
    in
    {
      devShells = builtins.mapAttrs (_: s: s.devShells) perSystem;
      apps = builtins.mapAttrs (_: s: s.apps) perSystem;
    };
}
