# Generated by nixty. Edit the nixty file it comes from instead; this file is overwritten.
{
  description = "Example 01: dev shells";

  inputs = {
    nixpkgs = {
      url = "github:NixOS/nixpkgs/nixos-25.05";
      flake = false;
    };
  };

  outputs =
    { self, nixpkgs, ... }:
    let
      perSystem = {
        x86_64-linux =
          let
            pkgs = import nixpkgs {
              system = "x86_64-linux";
              config = {
                allowUnfree = true;
              };
            };
          in
          {
            devShells = {
              dev = pkgs.mkShell {
                name = "dev";
                packages = [ pkgs.nodejs_22 pkgs.jq pkgs.ripgrep ];
                env = {
                  NODE_ENV = "development";
                };
                shellHook = "echo \"dev shell: node $(node --version)\"";
              };
              ci = pkgs.mkShell {
                name = "ci";
                packages = [ pkgs.nodejs_22 pkgs.shellcheck ];
                env = {
                  NODE_ENV = "test";
                };
                shellHook = "echo \"dev shell: node $(node --version)\"";
              };
            };
          };
      };
    in
    {
      devShells = builtins.mapAttrs (_: s: s.devShells) perSystem;
    };
}
