# Generated by nixty. Edit the nixty file it comes from instead; this file is overwritten.
{
  description = "Example 03: a command";

  inputs = {
    nixpkgs = {
      url = "github:NixOS/nixpkgs/nixos-25.05";
      flake = false;
    };
  };

  outputs =
    { self, nixpkgs, ... }:
    let
      perSystem = {
        x86_64-linux =
          let
            pkgs = import nixpkgs {
              system = "x86_64-linux";
              config = {
                allowUnfree = true;
              };
            };
          in
          {
            apps = {
              greet = {
                type = "app";
                program = pkgs.lib.getExe (pkgs.writeShellApplication {
                  name = "greet";
                  runtimeInputs = [ pkgs.figlet pkgs.cowsay pkgs.coreutils ];
                  text = ''
                    export GREETING=${pkgs.lib.escapeShellArg "Hello"}

                    name="''${1:-world}"
                    figlet "$GREETING, $name"
                    echo "Today is $(date +%A)" | cowsay

                  '';
                });
              };
            };
          };
      };
    in
    {
      apps = builtins.mapAttrs (_: s: s.apps) perSystem;
    };
}
