# Generated by nixty. Edit the nixty file it comes from instead; this file is overwritten.
{
  description = "Example 04: nixpkgs utilities";

  inputs = {
    nixpkgs = {
      url = "github:NixOS/nixpkgs/nixos-25.05";
      flake = false;
    };
  };

  outputs =
    { self, nixpkgs, ... }:
    let
      perSystem = {
        x86_64-linux =
          let
            pkgs = import nixpkgs {
              system = "x86_64-linux";
              config = {
                allowUnfree = true;
              };
            };
          in
          {
            devShells = {
              utils = pkgs.mkShell {
                name = "utils";
                packages = [
                  (pkgs.writeShellScriptBin "moo" "${pkgs.cowsay}/bin/cowsay \"moo\"")
                ];
                env = {
                  PROJECT = "${(import "${nixpkgs}/lib").strings.toUpper "nixty"}";
                  TOOLS = "${(import "${nixpkgs}/lib").strings.concatStringsSep ", " [ "moo" "cowsay" ]}";
                };
              };
            };
          };
      };
    in
    {
      devShells = builtins.mapAttrs (_: s: s.devShells) perSystem;
    };
}
