# Generated by nixty. Edit the nixty file it comes from instead; this file is overwritten.
{
  description = "A tour of Nixty";

  inputs = {
    nixpkgs = {
      url = "github:NixOS/nixpkgs/nixos-25.05";
      flake = false;
    };
  };

  outputs =
    { self, nixpkgs, ... }:
    let
      perSystem = {
        x86_64-linux =
          let
            pkgs = import nixpkgs {
              system = "x86_64-linux";
              config = {
                allowUnfree = true;
              };
            };
            hello = pkgs.stdenv.mkDerivation {
              pname = "hello";
              version = "1.0.0";
              src = ./.;
              nativeBuildInputs = [ pkgs.makeWrapper ];
              dontConfigure = true;
              dontBuild = true;
              installPhase = "install -Dm755 hello.sh $out/bin/hello";
              postFixup = ''
                for f in "$out"/bin/*; do
                  wrapProgram "$f" --prefix PATH : ${pkgs.lib.makeBinPath [ pkgs.figlet pkgs.cowsay ]}
                done'';
              meta = {
                description = "Says hello in big letters";
                license = pkgs.lib.licenses.mit;
                mainProgram = "hello";
              };
            };
          in
          {
            packages = {
              hello = hello;
            };
            devShells = {
              dev = pkgs.mkShell {
                name = "dev";
                packages = [ hello pkgs.shellcheck ];
                env = {
                  GREETING = "Hi";
                };
                shellHook = "echo \"Welcome! Try: hello, or shellcheck hello.sh\"";
              };
              dev-es = pkgs.mkShell {
                name = "dev-es";
                packages = [ hello pkgs.shellcheck ];
                env = {
                  GREETING = "Hola";
                };
                shellHook = "echo \"Welcome! Try: hello, or shellcheck hello.sh\"";
              };
            };
            apps = {
              lint = {
                type = "app";
                program = pkgs.lib.getExe (pkgs.writeShellApplication {
                  name = "lint";
                  runtimeInputs = [ pkgs.shellcheck ];
                  text = ''
                    shellcheck hello.sh && echo 'hello.sh looks good'
                  '';
                });
              };
            };
          };
        aarch64-darwin =
          let
            pkgs = import nixpkgs {
              system = "aarch64-darwin";
              config = {
                allowUnfree = true;
              };
            };
            hello = pkgs.stdenv.mkDerivation {
              pname = "hello";
              version = "1.0.0";
              src = ./.;
              nativeBuildInputs = [ pkgs.makeWrapper ];
              dontConfigure = true;
              dontBuild = true;
              installPhase = "install -Dm755 hello.sh $out/bin/hello";
              postFixup = ''
                for f in "$out"/bin/*; do
                  wrapProgram "$f" --prefix PATH : ${pkgs.lib.makeBinPath [ pkgs.figlet pkgs.cowsay ]}
                done'';
              meta = {
                description = "Says hello in big letters";
                license = pkgs.lib.licenses.mit;
                mainProgram = "hello";
              };
            };
          in
          {
            packages = {
              hello = hello;
            };
            devShells = {
              dev = pkgs.mkShell {
                name = "dev";
                packages = [ hello pkgs.shellcheck ];
                env = {
                  GREETING = "Hi";
                };
                shellHook = "echo \"Welcome! Try: hello, or shellcheck hello.sh\"";
              };
              dev-es = pkgs.mkShell {
                name = "dev-es";
                packages = [ hello pkgs.shellcheck ];
                env = {
                  GREETING = "Hola";
                };
                shellHook = "echo \"Welcome! Try: hello, or shellcheck hello.sh\"";
              };
            };
            apps = {
              lint = {
                type = "app";
                program = pkgs.lib.getExe (pkgs.writeShellApplication {
                  name = "lint";
                  runtimeInputs = [ pkgs.shellcheck ];
                  text = ''
                    shellcheck hello.sh && echo 'hello.sh looks good'
                  '';
                });
              };
            };
          };
      };
    in
    {
      packages = builtins.mapAttrs (_: s: s.packages) perSystem;
      devShells = builtins.mapAttrs (_: s: s.devShells) perSystem;
      apps = builtins.mapAttrs (_: s: s.apps) perSystem;
    };
}
