# Generated by nixty. Edit the nixty file it comes from instead; this file is overwritten.
{
  description = "A definition for this project";

  inputs = {
    nixpkgs = {
      url = "github:NixOS/nixpkgs/nixos-25.05";
      flake = false;
    };
    tools.url = "github:me/tools/v1.0";
  };

  outputs =
    { self, nixpkgs, tools, ... }:
    let
      perSystem = {
        x86_64-linux =
          let
            pkgs = import nixpkgs {
              system = "x86_64-linux";
              config = {
                allowUnfree = true;
              };
            };
            WeatherCLI = pkgs.stdenv.mkDerivation {
              pname = "WeatherCLI";
              version = "1.0.0";
              src = ./.;
              nativeBuildInputs = [ pkgs.nodejs_22 pkgs.makeWrapper ];
              propagatedBuildInputs = [ pkgs.go ];
              nativeCheckInputs = [ pkgs.vitest ];
              buildPhase = "npm run build -- --config ${pkgs.writeText "weather-config" "{\"city\":\"Mexico City\",\"units\":\"metric\"}"}";
              doCheck = true;
              installPhase = ''
                mkdir -p $out/bin
                cp dist/weather $out/bin/'';
              postFixup = ''
                for f in "$out"/bin/*; do
                  wrapProgram "$f" --prefix PATH : ${pkgs.lib.makeBinPath [ pkgs.nodejs_22 ]}
                done'';
              meta = {
                description = "Tells the weather of a city";
                license = pkgs.lib.licenses.mit;
                mainProgram = "weather";
              };
            };
          in
          {
            packages = {
              WeatherCLI = WeatherCLI;
            };
            devShells = {
              QA = pkgs.mkShell {
                name = "QA";
                packages = [
                  pkgs.nodejs_22
                  pkgs.go
                  tools.packages.x86_64-linux.cli
                  WeatherCLI
                ];
                env = {
                  HELLO = "THERE WE GO";
                };
                shellHook = "echo \"QA shell\"";
              };
              PROD = pkgs.mkShell {
                name = "PROD";
                packages = [ pkgs.gopls ];
                env = {
                  HELLO = "THERE WE GO";
                };
                shellHook = "echo \"QA shell\"";
              };
            };
            apps = {
              test = {
                type = "app";
                program = pkgs.lib.getExe (pkgs.writeShellApplication {
                  name = "test";
                  runtimeInputs = [ pkgs.nodejs_22 ];
                  text = ''
                    export CI=${pkgs.lib.escapeShellArg "1"}
                    npm test
                  '';
                });
              };
            };
          };
        aarch64-linux =
          let
            pkgs = import nixpkgs {
              system = "aarch64-linux";
              config = {
                allowUnfree = true;
              };
            };
            WeatherCLI = pkgs.stdenv.mkDerivation {
              pname = "WeatherCLI";
              version = "1.0.0";
              src = ./.;
              nativeBuildInputs = [ pkgs.nodejs_22 pkgs.makeWrapper ];
              buildInputs = [ pkgs.go ];
              propagatedBuildInputs = [ pkgs.go ];
              nativeCheckInputs = [ pkgs.vitest ];
              buildPhase = "npm run build -- --config ${pkgs.writeText "weather-config" "{\"city\":\"Mexico City\",\"units\":\"metric\"}"}";
              doCheck = true;
              installPhase = ''
                mkdir -p $out/bin
                cp dist/weather $out/bin/'';
              postFixup = ''
                for f in "$out"/bin/*; do
                  wrapProgram "$f" --prefix PATH : ${pkgs.lib.makeBinPath [ pkgs.nodejs_22 ]}
                done'';
              meta = {
                description = "Tells the weather of a city";
                license = pkgs.lib.licenses.mit;
                mainProgram = "weather";
              };
            };
          in
          {
            packages = {
              WeatherCLI = WeatherCLI;
            };
            devShells = {
              QA = pkgs.mkShell {
                name = "QA";
                packages = [
                  pkgs.nodejs_22
                  pkgs.go
                  tools.packages.aarch64-linux.cli
                  WeatherCLI
                ];
                env = {
                  HELLO = "THERE WE GO";
                };
                shellHook = "echo \"QA shell\"";
              };
              PROD = pkgs.mkShell {
                name = "PROD";
                packages = [ pkgs.gopls ];
                env = {
                  HELLO = "THERE WE GO";
                };
                shellHook = "echo \"QA shell\"";
              };
            };
            apps = { };
          };
      };
    in
    {
      packages = builtins.mapAttrs (_: s: s.packages) perSystem;
      devShells = builtins.mapAttrs (_: s: s.devShells) perSystem;
      apps = builtins.mapAttrs (_: s: s.apps) perSystem;
    };
}
