# Generated by nixty. Edit the nixty file it comes from instead; this file is overwritten.
{
  description = "weathercli — reporte del clima en la terminal";

  inputs = {
    nixpkgs = {
      url = "github:NixOS/nixpkgs/nixos-unstable";
      flake = false;
    };
  };

  outputs =
    { self, nixpkgs, ... }:
    let
      perSystem = {
        x86_64-linux =
          let
            pkgs = import nixpkgs {
              system = "x86_64-linux";
              config = {
                allowUnfree = true;
              };
            };
            weathercli = pkgs.stdenv.mkDerivation {
              pname = "weathercli";
              version = "1.0.0";
              src = ./.;
              nativeBuildInputs = [ pkgs.makeWrapper ];
              dontConfigure = true;
              dontBuild = true;
              installPhase = ''
                install -Dm755 weathercli.sh $out/bin/weathercli
                install -Dm644 ${pkgs.writeText "weathercli-config.json" "{\"city\":\"Mexico City\",\"units\":\"metric\",\"format\":\"compact\"}"} $out/share/weathercli/config.json'';
              postFixup = ''
                for f in "$out"/bin/*; do
                  wrapProgram "$f" --prefix PATH : ${pkgs.lib.makeBinPath [ pkgs.curl pkgs.jq ]}
                done
                wrapProgram $out/bin/weathercli --set-default WEATHERCLI_CONFIG $out/share/weathercli/config.json'';
              meta = {
                description = "Reporte del clima en la terminal, configurable vía un archivo JSON";
                license = pkgs.lib.licenses.mit;
                mainProgram = "weathercli";
              };
            };
          in
          {
            packages = {
              weathercli = weathercli;
            };
            devShells = {
              dev = pkgs.mkShell {
                name = "dev";
                packages = [ weathercli ];
                shellHook = "echo \"weathercli dev shell — corre 'weathercli' para probar\"";
              };
            };
          };
        aarch64-linux =
          let
            pkgs = import nixpkgs {
              system = "aarch64-linux";
              config = {
                allowUnfree = true;
              };
            };
            weathercli = pkgs.stdenv.mkDerivation {
              pname = "weathercli";
              version = "1.0.0";
              src = ./.;
              nativeBuildInputs = [ pkgs.makeWrapper ];
              dontConfigure = true;
              dontBuild = true;
              installPhase = ''
                install -Dm755 weathercli.sh $out/bin/weathercli
                install -Dm644 ${pkgs.writeText "weathercli-config.json" "{\"city\":\"Mexico City\",\"units\":\"metric\",\"format\":\"compact\"}"} $out/share/weathercli/config.json'';
              postFixup = ''
                for f in "$out"/bin/*; do
                  wrapProgram "$f" --prefix PATH : ${pkgs.lib.makeBinPath [ pkgs.curl pkgs.jq ]}
                done
                wrapProgram $out/bin/weathercli --set-default WEATHERCLI_CONFIG $out/share/weathercli/config.json'';
              meta = {
                description = "Reporte del clima en la terminal, configurable vía un archivo JSON";
                license = pkgs.lib.licenses.mit;
                mainProgram = "weathercli";
              };
            };
          in
          {
            packages = {
              weathercli = weathercli;
            };
            devShells = {
              dev = pkgs.mkShell {
                name = "dev";
                packages = [ weathercli ];
                shellHook = "echo \"weathercli dev shell — corre 'weathercli' para probar\"";
              };
            };
          };
        x86_64-darwin =
          let
            pkgs = import nixpkgs {
              system = "x86_64-darwin";
              config = {
                allowUnfree = true;
              };
            };
            weathercli = pkgs.stdenv.mkDerivation {
              pname = "weathercli";
              version = "1.0.0";
              src = ./.;
              nativeBuildInputs = [ pkgs.makeWrapper ];
              dontConfigure = true;
              dontBuild = true;
              installPhase = ''
                install -Dm755 weathercli.sh $out/bin/weathercli
                install -Dm644 ${pkgs.writeText "weathercli-config.json" "{\"city\":\"Mexico City\",\"units\":\"metric\",\"format\":\"compact\"}"} $out/share/weathercli/config.json'';
              postFixup = ''
                for f in "$out"/bin/*; do
                  wrapProgram "$f" --prefix PATH : ${pkgs.lib.makeBinPath [ pkgs.curl pkgs.jq ]}
                done
                wrapProgram $out/bin/weathercli --set-default WEATHERCLI_CONFIG $out/share/weathercli/config.json'';
              meta = {
                description = "Reporte del clima en la terminal, configurable vía un archivo JSON";
                license = pkgs.lib.licenses.mit;
                mainProgram = "weathercli";
              };
            };
          in
          {
            packages = {
              weathercli = weathercli;
            };
            devShells = {
              dev = pkgs.mkShell {
                name = "dev";
                packages = [ weathercli ];
                shellHook = "echo \"weathercli dev shell — corre 'weathercli' para probar\"";
              };
            };
          };
        aarch64-darwin =
          let
            pkgs = import nixpkgs {
              system = "aarch64-darwin";
              config = {
                allowUnfree = true;
              };
            };
            weathercli = pkgs.stdenv.mkDerivation {
              pname = "weathercli";
              version = "1.0.0";
              src = ./.;
              nativeBuildInputs = [ pkgs.makeWrapper ];
              dontConfigure = true;
              dontBuild = true;
              installPhase = ''
                install -Dm755 weathercli.sh $out/bin/weathercli
                install -Dm644 ${pkgs.writeText "weathercli-config.json" "{\"city\":\"Mexico City\",\"units\":\"metric\",\"format\":\"compact\"}"} $out/share/weathercli/config.json'';
              postFixup = ''
                for f in "$out"/bin/*; do
                  wrapProgram "$f" --prefix PATH : ${pkgs.lib.makeBinPath [ pkgs.curl pkgs.jq ]}
                done
                wrapProgram $out/bin/weathercli --set-default WEATHERCLI_CONFIG $out/share/weathercli/config.json'';
              meta = {
                description = "Reporte del clima en la terminal, configurable vía un archivo JSON";
                license = pkgs.lib.licenses.mit;
                mainProgram = "weathercli";
              };
            };
          in
          {
            packages = {
              weathercli = weathercli;
            };
            devShells = {
              dev = pkgs.mkShell {
                name = "dev";
                packages = [ weathercli ];
                shellHook = "echo \"weathercli dev shell — corre 'weathercli' para probar\"";
              };
            };
          };
      };
    in
    {
      packages = builtins.mapAttrs (_: s: s.packages) perSystem;
      devShells = builtins.mapAttrs (_: s: s.devShells) perSystem;
    };
}
