# Generated by nixty. Edit the nixty file it comes from instead; this file is overwritten.
{
  description = "Example 02: a package";

  inputs = {
    nixpkgs = {
      url = "github:NixOS/nixpkgs/nixos-25.05";
      flake = false;
    };
  };

  outputs =
    { self, nixpkgs, ... }:
    let
      perSystem = {
        x86_64-linux =
          let
            pkgs = import nixpkgs {
              system = "x86_64-linux";
              config = {
                allowUnfree = true;
              };
            };
          in
          {
            packages = {
              greeter = pkgs.stdenv.mkDerivation {
                pname = "greeter";
                version = "1.0.0";
                src = ./.;
                dontConfigure = true;
                doCheck = true;
                installPhase = ''
                  mkdir -p $out/bin
                  cp greeter $out/bin/'';
                meta = {
                  description = "Says hello";
                  license = pkgs.lib.licenses.mit;
                  mainProgram = "greeter";
                };
              };
            };
          };
      };
    in
    {
      packages = builtins.mapAttrs (_: s: s.packages) perSystem;
    };
}
